version: '3'
services:
  kodi:
    image: tkislan/kodi-simulator
    ports:
      - '8080:8080'
      - '5900:5900'
  app:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    environment:
      PYTHONPATH: /home/python/app/mock:/home/python/app/resources:/home/python/app/resources/lib:/home/python/app/tests
      KODI_HOST: http://kodi:8080
    volumes:
      - .:/home/python/app
    depends_on:
      - kodi
