version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.11

jobs:
  build:
    parameters:
      python_version:
        type: string
    docker:
      - image: circleci/python:<< parameters.python_version >>
      - image: tkislan/kodi-simulator
    environment:
      KODI_HOST: http://localhost:8080
    working_directory: ~/app
    steps:
      - checkout

      - run:
          name: Set PYTHONPATH environment variable
          command: echo 'export PYTHONPATH=${HOME}/app/mock:${HOME}/app/resources/lib:${HOME}/app/resources' >> $BASH_ENV

      - run:
          name: Export
          command: export

      - run:
          name: Install Test dependencies
          command: sudo pip install pylint flake8
      
      - run:
          name: Install Kodi dependencies
          command: sudo pip install future==0.17.1

      - restore_cache:
          key: dependencies-{{ checksum "install-dependencies.sh" }}

      - run:
          name: Install dependencies
          command: ./install-dependencies.sh

      - save_cache:
          key: dependencies-{{ checksum "install-dependencies.sh" }}
          paths:
            - "~/.cache/pip"

      - run:
          name: Run Linter
          command: ./run-linter.sh

      - run:
          name: Wait for kodi simulator
          command: ./wait-for-kodi-simulator.sh

      - run:
          name: Run tests
          command: python -m unittest discover -s tests/

      - run:
          name: Run Fuzzy tests
          environment:
            DISABLE_NGRAM_INDEX: "1"
          command: python -m unittest discover -s tests/

      - run:
          name: Create package
          command: ./create-package.sh

      - run: mkdir -p /tmp/package

      - run:
          name: Copy package
          command: cp -v plugin.video.kodiconnect-*.zip /tmp/package

      - persist_to_workspace:
          root: /tmp/package
          paths:
            - plugin.video.kodiconnect-*.zip

  upload_package:
    docker:
      - image: circleci/python:3.7
    steps:
      - attach_workspace:
          at: /tmp/package

      - aws-s3/sync:
          from: /tmp/package
          to: 's3://kodi-connect/kodi-connect-addon'


workflows:
  version: 2
  build-python-2.7:
    jobs:
      - build:
          python_version: "2.7"
      - upload_package:
          context: aws
          requires:
            - build
          filters:
            branches:
              only: master
  build-python-3.6:
    jobs:
      - build:
          python_version: "3.6"
      - upload_package:
          context: aws
          requires:
            - build
          filters:
            branches:
              only: master
